//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalSetter
{
    using System;
    using System.Collections.Generic;
    
    public partial class goal
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string duration { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> percent_compelete { get; set; }
    }
}
